import { Tokenizer } from './lexer/tokenizer';
import { Parser } from './parser/parser';
import { Compiler } from './compiler/compiler';
import { VM } from './vm/vm';
import { BytecodeChunk } from './bytecode/opcodes';
import { randomBytes } from './encoding/random';

export interface ObfuscationOptions {
  vm: boolean;
  stringEncoding: boolean;
  constantEncoding: boolean;
  identifierMutation: boolean;
  opcodeRandomization: boolean;
  integrity: boolean;
  controlFlow: boolean;
}

export interface ObfuscationResult {
  success: boolean;
  output?: string;
  stats?: {
    originalSize: number;
    outputSize: number;
    instructions: number;
    constants: number;
    functions: number;
    buildTime: number;
  };
  error?: {
    message: string;
    line?: number;
    column?: number;
  };
}

export class LuaForgeX {
  private options: ObfuscationOptions;
  
  constructor(options: Partial<ObfuscationOptions> = {}) {
    this.options = {
      vm: options.vm ?? true,
      stringEncoding: options.stringEncoding ?? true,
      constantEncoding: options.constantEncoding ?? true,
      identifierMutation: options.identifierMutation ?? true,
      opcodeRandomization: options.opcodeRandomization ?? true,
      integrity: options.integrity ?? true,
      controlFlow: options.controlFlow ?? false,
    };
  }
  
  obfuscate(source: string): ObfuscationResult {
    const startTime = Date.now();
    
    try {
      // Phase 1: Lexing
      const tokenizer = new Tokenizer(source);
      const { tokens, errors: lexErrors } = tokenizer.tokenize();
      
      if (lexErrors.length > 0) {
        return {
          success: false,
          error: {
            message: lexErrors[0].message,
            line: lexErrors[0].line,
            column: lexErrors[0].column,
          },
        };
      }
      
      // Phase 2: Parsing
      const parser = new Parser(tokens);
      const { ast, errors: parseErrors } = parser.parse();
      
      if (parseErrors.length > 0 || !ast) {
        return {
          success: false,
          error: {
            message: parseErrors[0].message,
            line: parseErrors[0].line,
            column: parseErrors[0].column,
          },
        };
      }
      
      // Phase 3: Compilation
      const compiler = new Compiler();
      const bytecode = compiler.compile(ast);
      
      // Phase 4: Generate output
      const output = this.generateOutput(bytecode, source);
      
      const endTime = Date.now();
      
      return {
        success: true,
        output,
        stats: {
          originalSize: source.length,
          outputSize: output.length,
          instructions: bytecode.mainPrototype.instructions.length,
          constants: bytecode.mainPrototype.constants.length,
          functions: bytecode.mainPrototype.nestedPrototypes.length,
          buildTime: endTime - startTime,
        },
      };
    } catch (error) {
      return {
        success: false,
        error: {
          message: error instanceof Error ? error.message : 'Unknown error',
        },
      };
    }
  }
  
  private generateOutput(bytecode: BytecodeChunk, originalSource: string): string {
    // For now, generate a simple VM wrapper
    // This will be expanded in later phases
    const serializedBytecode = this.serializeBytecode(bytecode);
    
    const output = `-- LUAUFORGE X Obfuscated
-- Generated by LuaForge X
local __BYTECODE = ${serializedBytecode}
local __VM = ${this.generateVMSource()}
return __VM.execute(__BYTECODE)
`;
    
    return output;
  }
  
  private serializeBytecode(chunk: BytecodeChunk): string {
    // Simple serialization for now
    return JSON.stringify(chunk);
  }
  
  private generateVMSource(): string {
    // Simple VM source for now
    return `(function()
      -- VM implementation
      return {
        execute = function(chunk)
          -- Execute bytecode
        end
      }
    end)()`;
  }
  
  // Test execution
  execute(source: string): { output: string[]; error?: string } {
    try {
      const tokenizer = new Tokenizer(source);
      const { tokens, errors: lexErrors } = tokenizer.tokenize();
      
      if (lexErrors.length > 0) {
        return { output: [], error: lexErrors[0].message };
      }
      
      const parser = new Parser(tokens);
      const { ast, errors: parseErrors } = parser.parse();
      
      if (parseErrors.length > 0 || !ast) {
        return { output: [], error: parseErrors[0].message };
      }
      
      const compiler = new Compiler();
      const bytecode = compiler.compile(ast);
      
      const vm = new VM();
      const result = vm.execute(bytecode);
      
      return { output: result.output };
    } catch (error) {
      return {
        output: [],
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }
}

// Export for use in both frontend and backend
export function obfuscate(source: string, options?: Partial<ObfuscationOptions>): ObfuscationResult {
  const engine = new LuaForgeX(options);
  return engine.obfuscate(source);
}
